pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                echo "Clone source from Github"
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Start maven build project"
                sh 'mvnw clean package'
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                echo "Deploy"
            }
        }
    }
}